[cellpose]
do_3D = false
stitch_threshold = 0.3

[data]
raw_path = "/groups/shroff/shrofflab/xinyi/HighSNR_embryo_SLS161/for_Caroline/raw/p4.tif"
nuclear_channel = 1  # 488, confirmed by eye against processed/p4-488_t1.tif
output_root = "/nrs/shroff/malinmayorc/cellpose_runner_test"
